name: docs

on:
# 每当 push 到 main 分支时触发部署
  push:
    branches:
      - main
    paths-ignore:
      - '**/__tests__/**'
  # 手动触发部署
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install
      - name: Build
        run: yarn docs:build

      # - name: CreateTag
      #   run git tag -a
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTION_SECRET }}
          publish_dir: docs/.vitepress/dist