name: docs

on:
# 每当 push 到 main 分支时触发部署
  push:
    branches:
      - main
    paths-ignore:
      - '**/__tests__/**'
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    env:
      DOCS_GA_ID: G-CTB8FQ7VMW
      NODE_VERSION: '16'

    steps:
      - uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          # 选择要使用的 node 版本
          node-version: '16'

      # 如果缓存没有命中，安装依赖
      - name: Install dependencies
        run: npm install --frozen-lockfile


      # 运行构建脚本
      - name: Build documentation site
        run: npm run docs:build


       # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
